### ISSUE TITLE
duration of .ts file shows 0

### ISSUE THREAD

**Issue by vimlesh1975** [Nicholi/MediaInfoDotNet#1]
I am using version .7.67.2
Other files duration is fine.
duration of .ts file shows 0

I am using it as below
 Dim mediainfofile2 As MediaInfoDotNet.MediaFile = New MediaInfoDotNet.MediaFile("c:/casparcg/_media/123.ts")
        Label2.Text = (mediainfofile2.duration).ToString

**Comment by nicholi** [comment]
I'm assuming you are referring to the binary builds available here? 

https://www.nuget.org/packages/MediaInfoDotNet/

These are not made by me but come from the upstream git I forked from.
http://git.vahanus.net/?p=csc/MediaInfoDotNet.git;a=summary
No idea how to contact those developers at all.

You may simply need to update the C binary for mediainfo though (they make lots of fixes all the time in the main mediainfo project), as I've had no trouble with .ts files. However a lot of different things could be in the .ts file, it's just a container. That doesn't say much about what is not working. And unless you build the project yourself I do not provide provide binaries for my fork of MediaInfoDotNet.
