### ISSUE TITLE
throws exception while not in debug mode !

### ISSUE THREAD

**Issue by ymg2006** [Nicholi/MediaInfoDotNet#3]
fix this line of file MediaInfoDotNet/MediaInfoDotNet/Models/Media.cs 

if (!String.IsNullOrEmpty(miResult) && !rc && **System.Diagnostics.Debugger.IsAttached**) {
System.Diagnostics.Debug.WriteLine("MediaInfo.dll returned NAN for parameter {0}", parameter);  System.Diagnostics.Debugger.Break();
}

**Comment by nicholi** [comment]
Failing to see the issue here?

You don't need to check if Debugger is attached. The System.Diagnostics.Debug and System.Diagnostics.Debugger classes skip most operations if the DEBUG compilation symbol isn't used. It's already built into the classes to do nothing.
